services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "8080:8080"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - RABBITMQ_HOST=metrics-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - AGGREGATION_GRPC_HOST=aggregation-service
      - AGGREGATION_GRPC_PORT=50052
      - MONITORING_HTTP_HOST=host.docker.internal
      - MONITORING_HTTP_PORT=8083
    restart: unless-stopped
    networks:
      - metrics-service_metrics-network

networks:
  metrics-service_metrics-network:
    external: true
